version: 2

project_name: dso

before:
  hooks:
    - go mod tidy

builds:
  - id: docker-dso
    main: ./cmd/dso
    binary: docker-dso
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

  - id: dso-provider-aws
    main: ./cmd/plugins/dso-provider-aws
    binary: dso-provider-aws
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

  - id: dso-provider-azure
    main: ./cmd/plugins/dso-provider-azure
    binary: dso-provider-azure
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

  - id: dso-provider-huawei
    main: ./cmd/plugins/dso-provider-huawei
    binary: dso-provider-huawei
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

  - id: dso-provider-vault
    main: ./cmd/plugins/dso-provider-vault
    binary: dso-provider-vault
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: dso
    ids:
      - docker-dso
      - dso-provider-aws
      - dso-provider-azure
      - dso-provider-huawei
      - dso-provider-vault
    name_template: "dso-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: "dso-{{ .Version }}-checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
