package bootstrap

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// knownProviders is the authoritative allowlist of valid provider names.
// Provider names are used directly in file paths; unknown names are rejected
// to prevent path traversal via crafted dso.yaml entries.
var knownProviders = map[string]bool{
	"aws": true, "azure": true, "vault": true, "huawei": true,
}

// ProviderPluginInstaller handles building and installing provider plugins
type ProviderPluginInstaller struct {
	logger Logger
	dryRun bool
}

// NewProviderPluginInstaller creates a new provider plugin installer
func NewProviderPluginInstaller(logger Logger, dryRun bool) *ProviderPluginInstaller {
	return &ProviderPluginInstaller{
		logger: logger,
		dryRun: dryRun,
	}
}

// InstallProviderPlugins builds and installs the required provider plugins
func (ppi *ProviderPluginInstaller) InstallProviderPlugins(ctx context.Context, providers []string) error {
	if len(providers) == 0 {
		ppi.logger.Info("No providers to install")
		return nil
	}

	// Determine plugin install directory based on permissions
	var pluginDir string
	if os.Geteuid() == 0 {
		// Running as root - use system-wide directory
		pluginDir = "/usr/local/lib/dso/plugins"
	} else {
		// Running as non-root - use user directory
		home, err := os.UserHomeDir()
		if err != nil {
			ppi.logger.Warn("Could not determine home directory, using system default")
			pluginDir = "/usr/local/lib/dso/plugins" // Fallback
		} else {
			pluginDir = filepath.Join(home, ".dso", "plugins")
		}
	}

	if ppi.dryRun {
		ppi.logger.Info("DRY_RUN: Would install provider plugins",
			"providers", providers,
			"directory", pluginDir)
		return nil
	}

	// Ensure plugin directory exists
	// #nosec G301 -- 0755 is deliberate: the "dso" group must be able to read+
	// execute plugin binaries here without sudo (README's Non-Root Operation
	// feature); SEC-2/SEC-3 already hardened write access via ownership, not
	// this read/execute bit
	if err := os.MkdirAll(pluginDir, 0755); err != nil {
		return fmt.Errorf("failed to create plugin directory %s: %w", pluginDir, err)
	}
	ppi.logger.Info("Plugin directory ready", "path", pluginDir)

	// Build and install each provider plugin
	for _, provider := range providers {
		if err := ppi.buildAndInstallPlugin(ctx, provider, pluginDir); err != nil {
			ppi.logger.Warn("Failed to install provider plugin, continuing anyway",
				"provider", provider, "error", err.Error())
			// Don't fail bootstrap if a single provider plugin fails
			// User can manually install later
			continue
		}
		ppi.logger.Info("Provider plugin installed", "provider", provider, "path", pluginDir)
	}

	// [SEC-2] Regenerate the hash manifest to cover every plugin binary
	// currently in pluginDir (not just ones built in this run), so
	// pkg/provider.LoadProvider's now-mandatory hash verification has a
	// manifest to check against after a normal setup run. Best-effort: a
	// manifest write failure is logged but does not fail bootstrap, since an
	// operator can regenerate manually and the alternative (fail loudly here)
	// would make bootstrap dependent on plugin-directory writability in a
	// context where it already tolerates individual plugin build failures.
	if err := ppi.writeHashManifest(pluginDir); err != nil {
		ppi.logger.Warn("Failed to write plugin hash manifest, provider plugins will fail hash verification until this is regenerated",
			"directory", pluginDir, "error", err.Error())
	}

	return nil
}

// writeHashManifest computes SHA256 hashes for every dso-provider-* binary in
// pluginDir and writes them to the default manifest file [SEC-2]. This is
// what makes pkg/provider.LoadProvider's mandatory-by-default hash
// verification work without extra operator steps after a standard install.
func (ppi *ProviderPluginInstaller) writeHashManifest(pluginDir string) error {
	entries, err := os.ReadDir(pluginDir)
	if err != nil {
		return fmt.Errorf("failed to read plugin directory: %w", err)
	}

	var lines []string
	lines = append(lines, "# Plugin Hash Manifest (auto-generated by docker dso system setup)")
	lines = append(lines, "# Format: plugin_name=sha256_hash")
	lines = append(lines, "")

	for _, entry := range entries {
		if entry.IsDir() || !strings.HasPrefix(entry.Name(), "dso-provider-") {
			continue
		}
		binPath := filepath.Join(pluginDir, entry.Name())
		hash, err := hashFile(binPath)
		if err != nil {
			ppi.logger.Warn("Failed to hash plugin binary for manifest", "path", binPath, "error", err.Error())
			continue
		}
		lines = append(lines, fmt.Sprintf("%s=%s", entry.Name(), hash))
	}

	manifestPath := filepath.Join(pluginDir, "hashes.txt")
	content := strings.Join(lines, "\n") + "\n"
	// 0644 matches this codebase's existing convention for plugin-directory
	// artifacts (the directory itself and each plugin binary are 0755) since
	// `setup` may run as root while the agent process verifying hashes at
	// runtime can run as a different, less-privileged user -- the manifest
	// must stay readable across that boundary. It holds no secrets, only
	// plugin names and SHA256 hashes of public binary content, so unlike a
	// credentials file this is not a confidentiality concern; only its write
	// path (root-owned directory, per SEC-3) matters for integrity.
	if err := os.WriteFile(manifestPath, []byte(content), 0644); err != nil { // #nosec G306
		return fmt.Errorf("failed to write manifest %s: %w", manifestPath, err)
	}
	ppi.logger.Info("Plugin hash manifest written", "path", manifestPath)
	return nil
}

// hashFile returns the lowercase hex SHA256 of the file at path.
func hashFile(path string) (string, error) {
	// #nosec G304 -- path comes from os.ReadDir(pluginDir) filtered to
	// "dso-provider-*" entries (see caller) -- DSO's own plugin directory
	// listing, not attacker/remote input
	f, err := os.Open(path)
	if err != nil {
		return "", err
	}
	defer func() { _ = f.Close() }()

	h := sha256.New()
	if _, err := io.Copy(h, f); err != nil {
		return "", err
	}
	return hex.EncodeToString(h.Sum(nil)), nil
}

// buildAndInstallPlugin builds and installs a single provider plugin
func (ppi *ProviderPluginInstaller) buildAndInstallPlugin(ctx context.Context, provider string, pluginDir string) error {
	if !knownProviders[provider] {
		return fmt.Errorf("unknown provider %q: must be one of aws, azure, vault, huawei", provider)
	}

	pluginBinary := filepath.Join(pluginDir, fmt.Sprintf("dso-provider-%s", provider))

	// Check if plugin already exists
	if _, err := os.Stat(pluginBinary); err == nil {
		ppi.logger.Info("Provider plugin already exists, skipping build",
			"provider", provider,
			"path", pluginBinary)
		return nil
	}

	// Map provider name to plugin command directory
	cmdDir := filepath.Join("cmd", "plugins", fmt.Sprintf("dso-provider-%s", provider))

	// Check if plugin source exists
	if _, err := os.Stat(cmdDir); err != nil {
		if os.IsNotExist(err) {
			ppi.logger.Warn("Provider plugin source not found - running from released binary",
				"provider", provider,
				"source_dir", cmdDir)
			ppi.logger.Warn("To install provider plugins, run:",
				"command", fmt.Sprintf("sudo docker dso system setup --provider %s", provider))
			return fmt.Errorf("provider plugin source not found (running from released binary)")
		}
		return fmt.Errorf("failed to stat plugin source: %w", err)
	}

	ppi.logger.Info("Building provider plugin from source", "provider", provider)

	// Build the plugin binary
	// #nosec G204 -- fixed command ("go build"); pluginBinary/cmdDir are
	// derived from the operator-supplied --provider flag on a build-from-source
	// path only reachable when running from source, not a released binary
	cmd := exec.CommandContext(ctx, "go", "build", "-o", pluginBinary, fmt.Sprintf("./%s", cmdDir))
	cmd.Stdout = nil
	cmd.Stderr = nil

	if err := cmd.Run(); err != nil {
		return fmt.Errorf("failed to build provider plugin %s: %w", provider, err)
	}

	// Make it executable
	// #nosec G302 -- this is a compiled binary that must be executable to be
	// launched via go-plugin's RPC handshake, not a sensitive data file;
	// G302's 0600-or-less guidance doesn't apply to intentionally-executable artifacts
	if err := os.Chmod(pluginBinary, 0755); err != nil {
		return fmt.Errorf("failed to chmod plugin binary: %w", err)
	}

	// Validate plugin works (smoke test)
	// #nosec G204 -- pluginBinary is the file this same function just built
	// in the line above, not external input
	testCmd := exec.CommandContext(ctx, pluginBinary, "--version")
	if err := testCmd.Run(); err != nil {
		ppi.logger.Warn("Provider plugin smoke test failed, but continuing",
			"provider", provider,
			"error", err.Error())
		// Warn but don't fail - plugin might work despite version command failing
	}

	ppi.logger.Info("Provider plugin built successfully",
		"provider", provider,
		"path", pluginBinary)

	return nil
}

// GetRequiredProviders returns list of providers to install based on configuration
func GetRequiredProviders(providers map[string]ProviderConfig) []string {
	seen := make(map[string]bool)
	var required []string

	for _, cfg := range providers {
		if !seen[cfg.Type] {
			required = append(required, cfg.Type)
			seen[cfg.Type] = true
		}
	}

	return required
}
